name: Pipeline

on:
  push:
    branches:
      - 'master'
      - 'feature**'
env:
  bucketname: jwaggon-bootcamp-2022-bucket

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm test

  deploy-feature:
    environment: dev
    if: startsWith(github.ref, 'refs/heads/feature')
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      stage: dev
      service: ${{github.ref_name}}
    steps:
      - uses: actions/checkout@v2

      - name: Assume the testing pipeline user role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::775564629368:role/github-actions-role-Role-JU555QQWQJ9R
          role-session-name: feature-deployment

      - run: npm ci
      - run: npm run deploy

  deploy-dev:
    environment: dev
    if: github.ref == 'refs/heads/master'
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      stage: dev
    steps:
      - uses: actions/checkout@v2

      - name: Assume the testing pipeline user role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::775564629368:role/github-actions-role-Role-JU555QQWQJ9R
          role-session-name: dev-deployment

      - run: npm ci
      - run: npm run deploy

  deploy-prod:
    environment: prod
    if: github.ref == 'refs/heads/master'
    needs: [deploy-dev]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      stage: prod
    steps:
      - uses: actions/checkout@v2

      - name: Assume the testing pipeline user role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::775564629368:role/github-actions-role-Role-JU555QQWQJ9R
          role-session-name: prod-deployment

      - run: npm ci
      - run: npm run deploy